const products = [
  {
    id: 1,
    name: "Fernet con Coca",
    description: "Fernet Branca con Coca-Cola bien fría.",
    price: 6500,
    image: "https://picsum.photos/300/200?random=1",
    category: "tragos",
  },
  {
    id: 2,
    name: "Mojito",
    description: "Ron, menta, lima, azúcar y soda.",
    price: 7000,
    image: "https://picsum.photos/300/200?random=2",
    category: "tragos",
  },
  {
    id: 3,
    name: "Caipirinha",
    description: "Cachaça, lima y azúcar.",
    price: 7200,
    image: "https://picsum.photos/300/200?random=3",
    category: "tragos",
  },
  {
    id: 4,
    name: "Combo Amigos",
    description: "Pizza grande + 4 bebidas.",
    price: 18000,
    image: "https://picsum.photos/300/200?random=4",
    category: "combos",
  },
  {
    id: 5,
    name: "Combo Pareja",
    description: "Hamburguesas dobles + papas + bebidas.",
    price: 15000,
    image: "https://picsum.photos/300/200?random=5",
    category: "combos",
  },
  {
    id: 6,
    name: "Quilmes Stout",
    description: "Cerveza negra de 473ml.",
    price: 4500,
    image: "https://picsum.photos/300/200?random=6",
    category: "cervezas",
  },
  {
    id: 7,
    name: "Patagonia Amber Lager",
    description: "Cerveza artesanal de color ámbar.",
    price: 5500,
    image: "https://picsum.photos/300/200?random=7",
    category: "cervezas",
  },
  {
    id: 8,
    name: "Limonada",
    description: "Limonada natural con menta y jengibre.",
    price: 3500,
    image: "https://picsum.photos/300/200?random=8",
    category: "sin alcohol",
  },
  {
    id: 9,
    name: "Smoothie de Frutilla",
    description: "Frutillas frescas y yogurt.",
    price: 4200,
    image: "https://picsum.photos/300/200?random=9",
    category: "sin alcohol",
  },
];

export default products;
